org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.useAndroidX=true
android.enableJetifier=true
android.compileSdkVersion=34
android.minSdkVersion=24
android.targetSdkVersion=34
